favicon: null
name: Richie Parsons
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5518498877063394
  brandStrength: 0.3025008582044393
  rhythmicContrast: 0.871878037462011
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  lightness: 0.1011502335313708
typography_spectrum: 0.7350158572662622
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9498208
analytics:
  twitter: null
  google: null
  facebook: null
